name:
  var testing
on:
  workflow_dispatch:

jobs:
  display-variables:
    # You can use configuration variables with the `vars` context for dynamic jobs
    runs-on: ubuntu-latest
    steps:
    - name: ${{ vars.VAR_KEY }}
      run: |
        echo "repository variable"
        echo "organization variable"
        echo "overridden variable"
        echo "variable from shell"
